/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import javax.swing.*;
import java.util.List;

/**
 * @author isnae
 */
public class InsertarForm extends javax.swing.JDialog {

    /**
     * Creates new form InsertarForm
     */
    public InsertarForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_zona = new javax.swing.JRadioButton();
        btn_barrio = new javax.swing.JRadioButton();
        btn_parada = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        panel_zona = new javax.swing.JPanel();
        tf_nombreZona = new javax.swing.JTextField();
        btn_aggZona = new javax.swing.JButton();
        panel_barrio = new javax.swing.JPanel();
        box_zonas = new javax.swing.JComboBox<>();
        tf_nombreBarrio = new javax.swing.JTextField();
        btn_aggBarrio = new javax.swing.JButton();
        panel_parada = new javax.swing.JPanel();
        box_barrios = new javax.swing.JComboBox<>();
        tf_nombreParada = new javax.swing.JTextField();
        btn_aggParada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Insertar Zona / Barrio / Parada");

        buttonGroup1.add(btn_zona);
        btn_zona.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_zona.setText("Zona");
        btn_zona.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btn_zonaItemStateChanged(evt);
            }
        });

        buttonGroup1.add(btn_barrio);
        btn_barrio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_barrio.setText("Barrio");
        btn_barrio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btn_barrioItemStateChanged(evt);
            }
        });

        buttonGroup1.add(btn_parada);
        btn_parada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_parada.setText("Parada");
        btn_parada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btn_paradaItemStateChanged(evt);
            }
        });

        jPanel2.setLayout(new java.awt.CardLayout());

        tf_nombreZona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_nombreZona.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre de Zona"));

        btn_aggZona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_aggZona.setText("Agregar");
        btn_aggZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aggZonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_zonaLayout = new javax.swing.GroupLayout(panel_zona);
        panel_zona.setLayout(panel_zonaLayout);
        panel_zonaLayout.setHorizontalGroup(
            panel_zonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_zonaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(tf_nombreZona, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_zonaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_aggZona, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        panel_zonaLayout.setVerticalGroup(
            panel_zonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_zonaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(tf_nombreZona, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(btn_aggZona, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jPanel2.add(panel_zona, "card2");

        box_zonas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        box_zonas.setBorder(javax.swing.BorderFactory.createTitledBorder("Elegir Zona"));

        tf_nombreBarrio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_nombreBarrio.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre del Barrio"));

        btn_aggBarrio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_aggBarrio.setText("Agregar");
        btn_aggBarrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aggBarrioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_barrioLayout = new javax.swing.GroupLayout(panel_barrio);
        panel_barrio.setLayout(panel_barrioLayout);
        panel_barrioLayout.setHorizontalGroup(
            panel_barrioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_barrioLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_barrioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nombreBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_zonas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_barrioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_aggBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        panel_barrioLayout.setVerticalGroup(
            panel_barrioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_barrioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(box_zonas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(tf_nombreBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btn_aggBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jPanel2.add(panel_barrio, "card3");

        box_barrios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        box_barrios.setBorder(javax.swing.BorderFactory.createTitledBorder("Elegir Barrio"));

        tf_nombreParada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tf_nombreParada.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre de Parada"));

        btn_aggParada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_aggParada.setText("Agregar");
        btn_aggParada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aggParadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_paradaLayout = new javax.swing.GroupLayout(panel_parada);
        panel_parada.setLayout(panel_paradaLayout);
        panel_paradaLayout.setHorizontalGroup(
            panel_paradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_paradaLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panel_paradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_nombreParada, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_barrios, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_paradaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_aggParada, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panel_paradaLayout.setVerticalGroup(
            panel_paradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_paradaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(box_barrios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tf_nombreParada, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btn_aggParada, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel2.add(panel_parada, "card4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btn_zona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_barrio)
                .addGap(103, 103, 103)
                .addComponent(btn_parada)
                .addGap(32, 32, 32))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_zona)
                    .addComponent(btn_barrio)
                    .addComponent(btn_parada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_zonaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btn_zonaItemStateChanged
        panel_parada.setVisible(false);
        panel_barrio.setVisible(false);
        panel_zona.setVisible(true);
    }//GEN-LAST:event_btn_zonaItemStateChanged

    private void btn_barrioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btn_barrioItemStateChanged
        panel_zona.setVisible(false);
        panel_parada.setVisible(false);

        box_zonas.removeAll();
        List<String> zonas = Principal.arbol.buscaZonas();
        for (String zona: zonas) {
            box_zonas.addItem(zona);
        }

        panel_barrio.setVisible(true);
    }//GEN-LAST:event_btn_barrioItemStateChanged

    private void btn_paradaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btn_paradaItemStateChanged
        panel_barrio.setVisible(false);
        panel_zona.setVisible(false);

        box_barrios.removeAll();
        List<String> barrios = Principal.arbol.buscarBarrios();
        for (String barrio: barrios) {
            box_barrios.addItem(barrio);
        }

        panel_parada.setVisible(true);
    }//GEN-LAST:event_btn_paradaItemStateChanged

    private void btn_aggZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aggZonaActionPerformed
        String nombre = tf_nombreZona.getText().trim();
        if (nombre.isEmpty()) return;
        String resultado = Principal.arbol.insertarZona(nombre);
        JOptionPane.showMessageDialog(this, resultado);

    }//GEN-LAST:event_btn_aggZonaActionPerformed

    private void btn_aggBarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aggBarrioActionPerformed
        Object zona = box_zonas.getSelectedItem();

        if (zona != null) {
            String nombre = tf_nombreBarrio.getText().trim();
            String resultado = Principal.arbol.insertarBarrio((String) zona, nombre);
            JOptionPane.showMessageDialog(this, resultado);
        }

    }//GEN-LAST:event_btn_aggBarrioActionPerformed

    private void btn_aggParadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aggParadaActionPerformed
        Object barrio = box_barrios.getSelectedItem();

        if (barrio != null) {
            String nombre = tf_nombreParada.getText().trim();
            String resultado = Principal.arbol.insertarParada((String) barrio, nombre);
            JOptionPane.showMessageDialog(this, resultado);
        }
    }//GEN-LAST:event_btn_aggParadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_barrios;
    private javax.swing.JComboBox<String> box_zonas;
    private javax.swing.JButton btn_aggBarrio;
    private javax.swing.JButton btn_aggParada;
    private javax.swing.JButton btn_aggZona;
    private javax.swing.JRadioButton btn_barrio;
    private javax.swing.JRadioButton btn_parada;
    private javax.swing.JRadioButton btn_zona;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_barrio;
    private javax.swing.JPanel panel_parada;
    private javax.swing.JPanel panel_zona;
    private javax.swing.JTextField tf_nombreBarrio;
    private javax.swing.JTextField tf_nombreParada;
    private javax.swing.JTextField tf_nombreZona;
    // End of variables declaration//GEN-END:variables
}
