/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import arbol.ArbolGeneral;
import grafo.Grafo;
import modelo.Parada;

import javax.swing.*;
import java.util.List;


/**
 * @author isnae
 */
public class Principal extends javax.swing.JFrame {
    public static ArbolGeneral arbol;
    public static Grafo grafo;


    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        // ── Árbol General ────────────────────────────────────────────────────
        arbol = new ArbolGeneral("Ciudad Nexo");

        // Zona Norte
        arbol.insertarZona("Zona Norte");
        arbol.insertarBarrio("Zona Norte", "Barrio Altos");
        arbol.insertarParada("Barrio Altos", "Terminal Norte");
        arbol.insertarParada("Barrio Altos", "Plaza Altos");
        arbol.insertarParada("Barrio Altos", "Av. Principal");
        arbol.insertarBarrio("Zona Norte", "Barrio Río");
        arbol.insertarParada("Barrio Río", "Puente Río");
        arbol.insertarParada("Barrio Río", "Costanera");

        // Zona Centro
        arbol.insertarZona("Zona Centro");
        arbol.insertarBarrio("Zona Centro", "Barrio Histórico");
        arbol.insertarParada("Barrio Histórico", "Plaza Central");
        arbol.insertarParada("Barrio Histórico", "Museo");
        arbol.insertarParada("Barrio Histórico", "Catedral");
        arbol.insertarBarrio("Zona Centro", "Barrio Comercial");
        arbol.insertarParada("Barrio Comercial", "Mercado");
        arbol.insertarParada("Barrio Comercial", "Shopping");

        // Zona Sur
        arbol.insertarZona("Zona Sur");
        arbol.insertarBarrio("Zona Sur", "Barrio Industrial");
        arbol.insertarParada("Barrio Industrial", "Fábrica");
        arbol.insertarParada("Barrio Industrial", "Depósito");
        arbol.insertarBarrio("Zona Sur", "Barrio Residencial");
        arbol.insertarParada("Barrio Residencial", "Parque Sur");
        arbol.insertarParada("Barrio Residencial", "Colegio");
        arbol.insertarParada("Barrio Residencial", "Terminal Sur");

        // ── Grafo (conexiones con pesos en minutos) ──────────────────────────
        grafo = new Grafo();

        grafo.agregarArista("Terminal Norte", "Plaza Altos", 3);
        grafo.agregarArista("Plaza Altos", "Av. Principal", 4);
        grafo.agregarArista("Av. Principal", "Puente Río", 5);
        grafo.agregarArista("Puente Río", "Costanera", 3);
        grafo.agregarArista("Costanera", "Plaza Central", 6);
        grafo.agregarArista("Av. Principal", "Plaza Central", 8);
        grafo.agregarArista("Plaza Central", "Museo", 2);
        grafo.agregarArista("Museo", "Catedral", 2);
        grafo.agregarArista("Plaza Central", "Mercado", 4);
        grafo.agregarArista("Mercado", "Shopping", 3);
        grafo.agregarArista("Shopping", "Fábrica", 7);
        grafo.agregarArista("Fábrica", "Depósito", 4);
        grafo.agregarArista("Depósito", "Parque Sur", 5);
        grafo.agregarArista("Parque Sur", "Colegio", 3);
        grafo.agregarArista("Colegio", "Terminal Sur", 4);
        grafo.agregarArista("Catedral", "Mercado", 3);
        grafo.agregarArista("Terminal Norte", "Plaza Central", 12);
        grafo.agregarArista("Parque Sur", "Mercado", 6);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_op1 = new javax.swing.JButton();
        btn_op2 = new javax.swing.JButton();
        btn_op3 = new javax.swing.JButton();
        btn_op4 = new javax.swing.JButton();
        btn_op5 = new javax.swing.JButton();
        btn_op6 = new javax.swing.JButton();
        btn_op7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Rutas");

        btn_op1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_op1.setText("Ver jerarquía geográfica (árbol BFS)");
        btn_op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_op1ActionPerformed(evt);
            }
        });

        btn_op2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_op2.setText("Buscar parada/zona/barrio en el árbol");
        btn_op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_op2ActionPerformed(evt);
            }
        });

        btn_op3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_op3.setText("Insertar nueva parada / zona / barrio");
        btn_op3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_op3ActionPerformed(evt);
            }
        });

        btn_op4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_op4.setText("Ver red de conexiones (grafo)");
        btn_op4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_op4ActionPerformed(evt);
            }
        });

        btn_op5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_op5.setText("Ruta mínima entre dos paradas (Dijkstra)");
        btn_op5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_op5ActionPerformed(evt);
            }
        });

        btn_op6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_op6.setText("Paradas de una zona + ruta mínima entre ellas");
        btn_op6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_op6ActionPerformed(evt);
            }
        });

        btn_op7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_op7.setText("Verificar conectividad del grafo");
        btn_op7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_op7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_op2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_op7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_op4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_op3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_op1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_op5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                        .addComponent(btn_op6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)))
                .addGap(201, 201, 201))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btn_op1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_op2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_op3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_op4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_op5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_op6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_op7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_op1ActionPerformed
        Opcion1 op1 = new Opcion1(this, true);

    }//GEN-LAST:event_btn_op1ActionPerformed

    private void btn_op2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_op2ActionPerformed
        String o = JOptionPane.showInputDialog(this, "Buscar por nombre");
        if (o != null && !o.isEmpty() ){
            arbol.buscar(o);
        }


    }//GEN-LAST:event_btn_op2ActionPerformed

    private void btn_op3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_op3ActionPerformed
        InsertarForm form = new InsertarForm(this, true);
    }//GEN-LAST:event_btn_op3ActionPerformed

    private void btn_op4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_op4ActionPerformed
        GrafoForm form = new GrafoForm(this, true);
    }//GEN-LAST:event_btn_op4ActionPerformed

    private void btn_op5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_op5ActionPerformed
        RutaMinima ruta = new RutaMinima(this, true);
    }//GEN-LAST:event_btn_op5ActionPerformed

    private void btn_op6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_op6ActionPerformed
        ParadasPorZona paradasPorZona = new ParadasPorZona(this, true);
    }//GEN-LAST:event_btn_op6ActionPerformed

    private void btn_op7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_op7ActionPerformed
       BFS bfs = new BFS(this, true);


    }//GEN-LAST:event_btn_op7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_op1;
    private javax.swing.JButton btn_op2;
    private javax.swing.JButton btn_op3;
    private javax.swing.JButton btn_op4;
    private javax.swing.JButton btn_op5;
    private javax.swing.JButton btn_op6;
    private javax.swing.JButton btn_op7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
